### ISSUE TITLE
movementStatus get null 

### ISSUE THREAD

**Issue by panchalAlpit** [hypertrack/sdk-views-android#8]
Always get null movement status.

**Comment by deniszpua** [comment]
Hey @panchalAlpit!
Can you re-check that device id is correct?
Please, ping me in [Slack](https://join.slack.com/t/hypertracksupport/shared_invite/enQtNDA0MDYxMzY1MDMxLTdmNDQ1ZDA1MTQxOTU2NTgwZTNiMzUyZDk0OThlMmJkNmE0ZGI2NGY2ZGRhYjY0Yzc0NTJlZWY2ZmE5ZTA2NjI) if you have any troubles with this.
